# http://docs.travis-ci.com/user/customizing-the-build/

language: java

sudo: false # faster builds

jdk:
 - oraclejdk8

install:
 - mvn install -Dmaven.javadoc.skip=true -Dsource.skip=true -DskipTests=true -Dgpg.skip=true

script:
 - mvn clean compile test -Dgpg.skip=true

after_success: 
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2
